# Generated by Django 4.1.3 on 2022-11-08 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('access_id', models.CharField(max_length=40)),
                ('access_secret', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=40)),
                ('endpoint_url', models.CharField(choices=[('openapi.tuyaus.com', 'America'), ('openapi.tuyacn.com', 'China'), ('openapi.tuyaeu.com', 'Europe'), ('openapi.tuyain.com', 'India'), ('openapi-ueaz.tuyaus.com', 'EasternAmerica'), ('openapi-weaz.tuyaeu.com', 'WesternEurope')], max_length=23)),
            ],
        ),
    ]
