# Generated by Django 4.1.3 on 2022-11-20 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_tuya_homes_geo_name_alter_tuya_homes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuya_homes',
            name='payload',
            field=models.JSONField(),
        ),
        migrations.RemoveField(
            model_name='tuya_homes',
            name='user',
        ),
        migrations.AddField(
            model_name='tuya_homes',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
