# Generated by Django 4.1.3 on 2022-11-20 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_alter_tuya_homes_payload_remove_tuya_homes_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tuya_rooms',
            new_name='TuyaDevices',
        ),
        migrations.RenameModel(
            old_name='Tuya_homes',
            new_name='TuyaHomes',
        ),
        migrations.RenameModel(
            old_name='Tuya_devices',
            new_name='TuyaRooms',
        ),
        migrations.RenameModel(
            old_name='User_settings',
            new_name='UserSettings',
        ),
    ]
