# Generated by Django 4.1.3 on 2022-11-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_tuyadevices'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuyaDevicesXxx',
            fields=[
                ('uuid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('local_key', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tuyahomerooms')),
            ],
        ),
    ]
