# Generated by Django 4.1.3 on 2022-11-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tuyadevicesxxx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuyaDevicesXxx',
            new_name='TuyaDevices',
        ),
    ]
