# Generated by Django 4.1.3 on 2022-11-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_id', models.CharField(max_length=40)),
                ('access_secret', models.CharField(max_length=40)),
                ('uid', models.CharField(max_length=40)),
                ('endpoint_url', models.CharField(choices=[('openapi.tuyaus.com', 'America'), ('openapi.tuyacn.com', 'China'), ('openapi.tuyaeu.com', 'Europe'), ('openapi.tuyain.com', 'India'), ('openapi-ueaz.tuyaus.com', 'EasternAmerica'), ('openapi-weaz.tuyaeu.com', 'WesternEurope')], max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='TuyaHomes',
            fields=[
                ('home_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('geo_name', models.CharField(max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TuyaHomeRooms',
            fields=[
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tuyahomes')),
            ],
        ),
        migrations.CreateModel(
            name='TuyaDevices',
            fields=[
                ('uuid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('owner_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('local_key', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tuyahomerooms')),
            ],
        ),
    ]
