# Generated by Django 4.1.3 on 2022-11-08 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='User_settings',
        ),
        migrations.RenameField(
            model_name='user_settings',
            old_name='user_id',
            new_name='user',
        ),
    ]
