# Generated by Django 4.1.3 on 2022-11-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tuya_devices_tuya_rooms_tuya_homes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuya_homes',
            old_name='home',
            new_name='home_id',
        ),
    ]
