# Generated by Django 4.1.3 on 2022-11-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tuya_homes_home_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuya_homes',
            name='geo_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tuya_homes',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
