# Generated by Django 4.1.3 on 2022-11-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_tuya_rooms_tuyadevices_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuyaRooms',
        ),
    ]
