# Generated by Django 4.1.3 on 2022-11-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_tuyarooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuyaHomeRooms',
            fields=[
                ('room_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.tuyahomes')),
            ],
        ),
    ]
