# Generated by Django 4.1.3 on 2022-11-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tuyahomerooms_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuyaDevices',
        ),
    ]
